{{-- Generated by `sloppy rules --format=boost`. Edits are overwritten on the next run. --}}
@verbatim
# Sloppy: code rules for this repository

Instructions for coding agents working in this repository.

Generated by Sloppy 1.1.1 (`sloppy rules --format=boost`). Re-run it when the configuration changes.

## Before you call a task finished

Run the analyser over your own change and fix what it introduced:

```bash
vendor/bin/sloppy diff main --fail-on=high
```

Inherited findings are not yours to fix in passing. New ones are.

## This project

- Analysed paths: app
- Framework rules: auto
- Fails on: high and above
- Confidence floor: 0

## The 25 rules in force

### SL101 God Method

- Category: Complexity, severity: high
- Flags: Flags methods that are excessively long, branchy or chatty across several independent measurements.
- Why it costs: A method this size usually holds several unrelated responsibilities, which makes it hard to name, hard to test in isolation and hard to change without reading all of it. Length alone is not the problem: this fires when size, branching and the number of collaborators grow together. A lookup table -- a match or switch mapping constants to constants -- counts as one decision, and its rows do not count towards size. A method that is one statement building a value, such as a form or table definition, is only reported when it also branches or nests past the limits.
- Write it this way instead: Give a method one job. Extract each block you would have introduced with a comment into a named private method, or into its own action class.

### SL102 God Class

- Category: Complexity, severity: high
- Flags: Flags classes that are large across several dimensions at once: size, method count, injected dependencies and the number of collaborators they talk to.
- Why it costs: Method count on its own says very little -- an Eloquent model with twenty accessors is fine. This fires when size, dependency count and the breadth of collaborators rise together, which is the shape of a class that has absorbed several responsibilities and now has several reasons to change. Getters and fluent setters do not count as methods, classes built on a framework base get wider limits, and a class that talks to few collaborators needs one more signal than usual.
- Write it this way instead: Split the class by responsibility. If its honest description needs the word "and", it is two classes.

### SL103 Excessive Nesting

- Category: Complexity, severity: medium
- Flags: Flags methods whose conditionals, loops and try blocks nest deeper than the configured limit.
- Why it costs: Every level of nesting is another condition the reader has to keep in their head to know whether a line runs. Deeply nested code also tends to hide its happy path at the bottom of the well. Closures are not counted as nesting, because passing one to a transaction or a collection pipeline is idiomatic rather than a smell.
- Write it this way instead: Return early. Put the guard clauses at the top and leave the work at one level of indentation.

### SL104 Duplicate Logic

- Category: Duplication, severity: medium
- Flags: Flags methods whose bodies are structurally identical to another method in the project.
- Why it costs: Two methods with the same structure and the same calls tend to drift apart: a fix applied to one copy silently leaves the other broken. Because variable names and literals are normalised away, a match means the code has the same shape -- confirm the behaviour really is the same before merging them.
- Write it this way instead: Name the shared behaviour and call it from both places. If you cannot name it, the duplication is telling you the two cases are not the same case.

### SL105 Dead Private Method

- Category: Dead code, severity: medium
- Flags: Flags private methods with no visible caller anywhere in the declaring file.
- Why it costs: A private method can only be called from within its own class, so an unreferenced one is very likely dead: it still has to be read, understood and kept compiling. Calls from traits the class uses count as callers. Anything that could be reached indirectly -- magic methods, dynamic calls, a name appearing as a string, attributes -- is skipped rather than guessed at.
- Write it this way instead: Delete private code nothing calls. Version control remembers it for you.

### SL106 Unused Constructor Dependency

- Category: Dependencies, severity: medium
- Flags: Flags constructor-injected dependencies that are never read anywhere in the class.
- Why it costs: An unused dependency still has to be constructed and resolved, and it misleads the next reader about what the class actually needs. Only private properties are reported outright: a public one is part of the class's API and any caller may read it, and a protected one belongs to subclasses. Reads inside traits the class uses count as uses. Dependencies that could be consumed indirectly -- through a parent class, dynamic property access or an attribute -- are skipped rather than guessed at.
- Write it this way instead: Inject only what the class uses. Every unused dependency is a line of setup in every test that constructs it.

### SL107 Swallowed Exception

- Category: Error handling, severity: high
- Flags: Flags catch blocks that neither rethrow, report, log nor otherwise react to the failure they caught.
- Why it costs: A catch block that does nothing observable turns a failure into a silent wrong answer: the caller sees null or false and cannot tell a genuine empty result from a crash, and nothing is recorded for anyone to investigate later. Catches that log, report, rethrow or record state are not flagged. A catch that answers with the value its signature already uses for "no" -- false from a bool predicate, or null from a nullable function after a specific exception -- is rated low.
- Write it this way instead: Handle the failure or let it travel. If you catch, log the exception as the previous one and rethrow something meaningful -- never return null in place of an answer.

### SL108 Redundant Condition

- Category: Readability, severity: low
- Flags: Flags conditions re-tested immediately inside themselves, repeated within one if/elseif chain, duplicated across a boolean operator, or written as a literal true/false.
- Why it costs: A condition that has already been established cannot change the outcome, so re-testing it adds a branch the reader has to verify and a branch tests can never cover. It usually appears when code is assembled from pieces that each defended themselves.
- Write it this way instead: Drop conditions that cannot be false. A null check on a non-nullable value teaches the next reader that it can be null.

### SL109 Narrative Comment

- Category: Readability, severity: low
- Flags: Flags short comments whose every meaningful word already appears in the statement directly below them.
- Why it costs: A comment that repeats the code costs a line to read and gains nothing, and it silently goes stale when the code changes. Comments explaining why a decision was made are not flagged, because their words are not in the code. This rule is subjective by nature -- turn it off if it does not match how your team writes.
- Write it this way instead: Write comments that say why, not what. If a comment restates the line below it, rename the thing and delete the comment.

### SL110 Defensive Programming Noise

- Category: Readability, severity: low
- Flags: Flags a method that guards the same subject the same way twice, with the same outcome and no reassignment in between.
- Why it costs: A guard repeated in different words reads as though it protects against something new, so the next reader spends time working out the difference and finds none. It also suggests the two checks were written at different times without either author reading the other.
- Write it this way instead: Validate at the boundary once and trust your own types afterwards. Re-checking a typed argument in every method downstream is noise that hides the check that matters.

### SL111 Copy-Paste Drift

- Category: Duplication, severity: high
- Flags: Flags a method body that is nearly identical to one or more siblings, where the difference looks like an unfinished copy rather than a deliberate variation.
- Why it costs: A body that matches its siblings everywhere but one place was probably copied and then edited in one copy only -- a guard added here and not there, a comparison flipped, a different class constructed. Structural duplication detection cannot see this, because it is looking for bodies that match exactly, and exact matches are the case where there is no bug. Confirm which copy is right before changing either: the majority is not automatically correct, it is only the more likely to be.
- Write it this way instead: Copies drift. When two blocks started identical and one has changed, either re-unify them or make the difference explicit -- a divergence nobody chose is a bug waiting for its turn.

### SL501 Unexplained Suppression

- Category: Suppression, severity: medium
- Flags: Flags static-analysis suppressions that give no reason for silencing the analyser.
- Why it costs: A suppression is a claim that the analyser is wrong about this line. Written with a reason it is a reviewed decision someone can check and eventually delete; written bare it is permanent, because no later reader can tell what it was protecting or whether the problem is still there.
- Write it this way instead: Fix the error rather than silencing it. If you must suppress, say why in the same comment -- an ignore with no reason can never be removed, because nobody can tell what it was protecting.

### SL201 Business Logic In Controller

- Category: Laravel, severity: high
- Flags: Flags controller actions that combine several business concerns: database writes, calculations, transactions, outbound calls and branching.
- Why it costs: Logic in a controller can only be exercised through an HTTP request, so it is harder to test, impossible to reuse from a command or a job, and it usually mixes transport concerns with domain rules. A small action that delegates is not flagged -- this fires when several independent business concerns pile up in one method.
- Write it this way instead: Keep controllers to translating HTTP into one call and back. Put the decision in an action, a service or the model.

### SL202 Inline Validation

- Category: Laravel, severity: low
- Flags: Flags large inline validation rule sets inside controllers, where a FormRequest would carry them better.
- Why it costs: A large inline rule set puts input contract, authorisation and business flow in one method, and nothing else can reuse the rules. A FormRequest gives the contract a name and a test, and leaves the controller to the flow. Small inline checks are not flagged.
- Write it this way instead: Validate in a FormRequest, or in a single validate() call. Hand-rolled if-blocks drift away from the rules the API documents.

### SL203 Possible N+1

- Category: Performance, severity: medium
- Flags: Flags relationship access inside a loop where the iterated collection does not appear to eager load that relation.
- Why it costs: Reading a relationship on each item of a collection issues one query per item, so a page that looks fine with ten rows falls over with ten thousand. This is reported as possible rather than certain: the relation may have been eager loaded somewhere this rule cannot see, in which case the access is free.
- Write it this way instead: Eager-load what the loop will touch: with() the relations before you iterate, not inside the iteration.

### SL204 Query Inside Loop

- Category: Performance, severity: medium
- Flags: Flags query builder or Eloquent queries executed inside a loop.
- Why it costs: Each iteration issues its own round trip to the database, so cost grows with the size of the collection and most of the work is the same query with a different value. One query before the loop, keyed by the value the loop varies, usually replaces all of them. Writes are the same: one insert or upsert after the loop replaces a create per row, and one bulk write per chunk is not reported.
- Write it this way instead: Hoist the query out of the loop. One whereIn beats N wheres, and the database will thank you at the size you have not reached yet.

### SL205 Collection Instead Of Database Query

- Category: Performance, severity: medium
- Flags: Flags a full table load followed immediately by a collection operation the database could have performed.
- Why it costs: Loading every row to filter, count or sort it in PHP uses memory proportional to the table and throws most of the work away. Collection operations are not the problem -- doing them to rows that were fetched only to be discarded is.
- Write it this way instead: Filter in the database. get()->filter() loads the table into memory to throw most of it away.

### SL206 Excessive Controller Dependencies

- Category: Dependencies, severity: medium
- Flags: Flags controllers whose constructor injects more collaborators than the configured limit.
- Why it costs: Every constructor dependency is resolved on every request that touches the controller, and a long list is a reliable sign that unrelated actions have been grouped into one class. Splitting by the dependencies each action actually needs usually produces several small, obvious controllers.
- Write it this way instead: Group the dependencies into a collaborator with a name. A controller with six of them is coordinating six things.

### SL207 Excessive Service Dependencies

- Category: Dependencies, severity: medium
- Flags: Flags service, action and manager classes whose constructor injects more collaborators than the configured limit.
- Why it costs: Coordination is a service's job, so several dependencies are normal. Past a point the class is coordinating more than one workflow, which shows up as tests that need half the container mocked and changes that touch the class for unrelated reasons. Only collaborators are counted: enums, value objects, models, dates and collections are data the class is built from, not dependencies.
- Write it this way instead: Group the dependencies into a collaborator with a name. A service with six of them is doing six jobs badly.

### SL208 Direct External API Call

- Category: Laravel, severity: medium
- Flags: Flags outbound HTTP requests made directly from controllers, models, form requests or middleware.
- Why it costs: An HTTP call in these layers cannot be exercised without either the network or framework-wide faking, and the endpoint, headers and payload shape end up spread across code that should not know them. Behind one named client, the integration can be swapped, retried, logged and faked in a single place.
- Write it this way instead: Put the HTTP call behind a small client class, so the timeout, the retry and the fake used in tests live in one place.

### SL209 Model Doing Too Much

- Category: Laravel, severity: medium
- Flags: Flags Eloquent models that make outbound calls, dispatch notifications or jobs, or contain long business workflows.
- Why it costs: Behaviour on a model runs wherever the model is loaded, including in factories, seeders and tests, and it is reachable from anywhere the model is. Persistence, relations and presentation of a row belong on the model; deciding what the business should do next generally does not.
- Write it this way instead: Keep models about data and relationships. Notifications, PDFs and payment calls belong in classes named after those things.

### SL210 Suspicious Model::all()

- Category: Performance, severity: medium
- Flags: Flags Model::all() whose result is iterated in the same method, or which is called from inside a loop.
- Why it costs: A full table load uses memory proportional to the table, which is invisible in development and fatal once the table grows. Where every row genuinely is needed, chunking or a lazy cursor gives the same result with bounded memory. Small reference tables are exempt via the ignore_models option.
- Write it this way instead: Ask for what you need: a where, a select, or pagination. Model::all() loads the whole table before you filter it.

### SL301 Abstraction Inflation

- Category: Architecture, severity: medium
- Flags: Flags concepts wrapped in several layers where at least one layer is trivial, singly implemented or singly used.
- Why it costs: Layers pay for themselves when they hide a real choice: a second implementation, a boundary that gets faked, a shape the caller should not see. When each layer has one implementation, one caller and almost no code, the indirection is all cost -- more files to open to follow one call, and no flexibility gained. This is a judgement about the current usage, not a rule against repositories.
- Write it this way instead: Add a layer when a second implementation or a real test seam needs it -- not in advance. Interfaces are cheap to add later and expensive to read past.

### SL302 Empty Wrapper Class

- Category: Architecture, severity: medium
- Flags: Flags classes whose public methods almost all forward their arguments unchanged to a single injected collaborator.
- Why it costs: Pure forwarding means callers pay an extra hop and an extra file to read, while the wrapper has to be kept in step with whatever it wraps. A wrapper becomes worthwhile the moment it does something of its own -- adapting a shape, adding caching, narrowing an interface -- and this rule stays quiet as soon as it does.
- Write it this way instead: A class that only forwards to another is a rename with extra steps. Call the other one.

### SL303 Single-Use Abstraction

- Category: Architecture, severity: low
- Flags: Flags small interfaces and abstract classes that have exactly one implementation and at most one calling file.
- Why it costs: An interface earns its keep by letting callers not care which implementation they got. With one implementation and one caller there is no choice being hidden, so the interface mostly duplicates the class signature and doubles the edits every change needs. This is advice, not a defect: keep it if a second implementation or a test double is genuinely on the way.
- Write it this way instead: An interface with one implementation and one caller is indirection with nothing on the other side. Inline it until a second implementation shows up.
@endverbatim
