<?php

declare(strict_types=1);

// Generated by `sloppy --format=rector`. Run it with:
//
//     vendor/bin/rector process --config=rector-sloppy.php
//
// Fixes 26 of 257 finding(s) in this run.
// SL101 x57: no automated fix -- splitting a long method is a design decision, not a rewrite.
// SL102 x14: no automated fix -- which responsibility leaves the class is a design decision.
// SL104 x9: no automated fix -- the shared code has to be named before it can be extracted.
// SL109 x110: no automated fix -- deleting a comment automatically risks deleting the one that mattered.
// SL111 x16: no automated fix -- only you know whether the drift between the copies was deliberate.
// SL201 x1: no automated fix.
// SL203 x3: no automated fix.
// SL204 x18: no automated fix.
// SL209 x2: no automated fix.
// SL210 x1: no automated fix.

use Rector\CodeQuality\Rector\Catch_\ThrowWithPreviousExceptionRector;
use Rector\CodeQuality\Rector\If_\CombineIfRector;
use Rector\CodeQuality\Rector\If_\SimplifyIfNotNullReturnRector;
use Rector\Config\RectorConfig;
use Rector\DeadCode\Rector\ClassMethod\RemoveUnusedConstructorParamRector;
use Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPromotedPropertyRector;
use Rector\DeadCode\Rector\If_\RemoveAlwaysTrueIfConditionRector;
use Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector;
use Rector\DeadCode\Rector\TryCatch\RemoveDeadTryCatchRector;
use Rector\EarlyReturn\Rector\Foreach_\ChangeNestedForeachIfsToEarlyContinueRector;
use Rector\EarlyReturn\Rector\If_\ChangeNestedIfsToEarlyReturnRector;

return RectorConfig::configure()
    ->withPaths([
        __DIR__.'/app/Jobs/Mikrotik/PingRouterJob.php',
        __DIR__.'/app/Models/Invoice.php',
        __DIR__.'/app/Services/CustomerDocumentService.php',
        __DIR__.'/app/Services/Geospatial/GeoJsonParser.php',
        __DIR__.'/app/Services/Geospatial/KmlParser.php',
        __DIR__.'/app/Services/Mikrotik/MikrotikService.php',
        __DIR__.'/app/Services/PaymentGateway/Drivers/XenditDriver.php',
        __DIR__.'/app/Services/Whatsapp/WhatsappService.php',
        __DIR__.'/app/Services/Whatsapp/WhatsappWebhookService.php',
    ])
    ->withRules([
        ThrowWithPreviousExceptionRector::class,
        CombineIfRector::class,
        SimplifyIfNotNullReturnRector::class,
        RemoveUnusedConstructorParamRector::class,
        RemoveUnusedPromotedPropertyRector::class,
        RemoveAlwaysTrueIfConditionRector::class,
        RemoveUnusedPrivatePropertyRector::class,
        RemoveDeadTryCatchRector::class,
        ChangeNestedForeachIfsToEarlyContinueRector::class,
        ChangeNestedIfsToEarlyReturnRector::class,
    ]);
