<?php

namespace Database\Factories;

use App\Enums\StatusInvoice;
use App\Models\Invoice;
use App\Models\LayananPelanggan;
use App\Models\Pelanggan;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Invoice>
 */
class InvoiceFactory extends Factory
{
    protected $model = Invoice::class;

    public function definition(): array
    {
        $harga = 250000;

        return [
            'no_invoice' => null, // Auto-generated by model booting
            'periode_tagihan' => now()->format('Y-m'),
            'pelanggan_id' => Pelanggan::factory(),
            'layanan_pelanggan_id' => LayananPelanggan::factory(),
            'jumlah' => $harga,
            'jumlah_setelah_promo' => $harga,
            'promo_id' => null,
            'status' => StatusInvoice::MenungguPembayaran,
            'tanggal_terbit' => now()->startOfMonth(),
            'tanggal_jatuh_tempo' => now()->startOfMonth()->addDays(7),
            'tanggal_lunas' => null,
            'metode_pembayaran' => null,
            'dibuat_oleh' => null,
            'dihapus_oleh' => null,
            'keterangan_hapus' => null,
        ];
    }

    public function lunas(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => StatusInvoice::Lunas,
            'tanggal_lunas' => now(),
            'metode_pembayaran' => 'manual_admin',
        ]);
    }
}
