<?php

namespace Database\Factories;

use App\Enums\Ticket\DivisiTicket;
use App\Enums\Ticket\JenisTicket;
use App\Enums\Ticket\PrioritasTicket;
use App\Enums\Ticket\StatusTicket;
use App\Enums\Ticket\SumberTicket;
use App\Models\Pelanggan;
use App\Models\Ticket;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Ticket>
 */
class TicketFactory extends Factory
{
    protected $model = Ticket::class;

    public function definition(): array
    {
        return [
            'nomor_ticket' => null, // Auto-generated by model booting
            'jenis' => JenisTicket::Gangguan,
            'pelanggan_id' => Pelanggan::factory(),
            'layanan_pelanggan_id' => null,
            'prioritas' => PrioritasTicket::Sedang,
            'divisi' => DivisiTicket::Teknisi,
            'pic_id' => null,
            'status' => StatusTicket::Baru,
            'sumber' => SumberTicket::Manual,
            'sla_target_selesai' => null, // Auto-generated by model booting
            'perlu_aktivasi_manual' => false,
            'deskripsi' => fake()->paragraph(),
            'dijadwalkan_pada' => null,
            'dibuat_oleh' => User::factory(),
        ];
    }

    public function pemasangan(): static
    {
        return $this->state(fn (array $attributes) => [
            'jenis' => JenisTicket::Pemasangan,
            'divisi' => DivisiTicket::Teknisi,
        ]);
    }

    public function gangguan(): static
    {
        return $this->state(fn (array $attributes) => [
            'jenis' => JenisTicket::Gangguan,
            'divisi' => DivisiTicket::Noc,
        ]);
    }

    public function diproses(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => StatusTicket::Diproses,
        ]);
    }

    public function selesai(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => StatusTicket::Selesai,
        ]);
    }

    public function darurat(): static
    {
        return $this->state(fn (array $attributes) => [
            'prioritas' => PrioritasTicket::Darurat,
        ]);
    }
}
