worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;

    server_tokens off;

    client_max_body_size 420m;

    server {
        listen 80;
        server_name _;

        root /var/www/html/public;
        index index.php;

        location = /up {
            try_files $uri /index.php?$query_string;
        }

        location ^~ /build/assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";

            try_files $uri =404;
        }

        location ~* ^/flux/(flux|editor)(\.min)?\.(js|css)$ {
            expires off;

            try_files $uri /index.php?$query_string;
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            try_files $uri =404;

            include fastcgi_params;

            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $document_root;

            fastcgi_read_timeout 60;
            fastcgi_send_timeout 60;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}