[PHP]

expose_php = Off

memory_limit = 512M

max_execution_time = 60
max_input_time = 60

post_max_size = 420M
upload_max_filesize = 400M

realpath_cache_size = 32M
realpath_cache_ttl = 720

register_argc_argv = Off


[OPcache]

opcache.enable = 1
opcache.enable_cli = 0

opcache.memory_consumption = 512
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 32531

opcache.max_file_size = 0
opcache.validate_timestamps = 0

opcache.save_comments = 1
opcache.use_cwd = 0


[JIT]

opcache.jit = disable
opcache.jit_buffer_size = 0