<?php

return [
    'standalone' => [
        [
            'title' => 'Dashboard',
            'icon' => 'home',
            'route' => 'dashboard',
            'active' => 'dashboard',
            'permission' => null,
        ],
    ],
    'groups' => [
        [
            'heading' => 'Pelanggan',
            'icon' => 'user-group',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Data Pelanggan',
                    'icon' => 'user-group',
                    'route' => 'pelanggan.index',
                    'active' => 'pelanggan.*',
                    'permission' => 'pelanggan.lihat',
                ],
                [
                    'title' => 'Data Registrasi Billing',
                    'icon' => 'signal',
                    'route' => 'layanan-pelanggan.index',
                    'active' => 'layanan-pelanggan.*',
                    'permission' => 'layanan_pelanggan.lihat',
                ],
                [
                    'title' => 'Maps Lokasi',
                    'icon' => 'map',
                    'route' => 'maps.index',
                    'active' => 'maps.lokasi',
                    'permission' => 'pelanggan.lihat',
                ],
                [
                    'title' => 'Estimasi Kabel',
                    'icon' => 'calculator',
                    'route' => 'maps.estimasi-kabel',
                    'active' => 'maps.estimasi-kabel',
                    'permission' => 'pelanggan.lihat',
                ],
                [
                    'title' => 'Laporan Data Layanan',
                    'icon' => 'table-cells',
                    'route' => 'laporan.layanan',
                    'active' => 'laporan.layanan',
                    'permission' => 'laporan.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Keuangan',
            'icon' => 'banknotes',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Tagihan (Invoice)',
                    'icon' => 'document-text',
                    'route' => 'invoice.index',
                    'active' => 'invoice.*',
                    'permission' => 'invoice.lihat',
                ],
                [
                    'title' => 'Riwayat Pembayaran',
                    'icon' => 'banknotes',
                    'route' => 'pembayaran.index',
                    'active' => 'pembayaran.index',
                    'permission' => 'pembayaran.lihat',
                ],
                [
                    'title' => 'Transaksi Gateway',
                    'icon' => 'credit-card',
                    'route' => 'pembayaran.transaksi-gateway.index',
                    'active' => 'pembayaran.transaksi-gateway.*',
                    'permission' => 'pembayaran.lihat',
                ],
                [
                    'title' => 'RAB Kantor',
                    'icon' => 'clipboard-document-list',
                    'route' => 'rab.index',
                    'active' => 'rab.*',
                    'permission' => 'rab.lihat',
                ],
                [
                    'title' => 'Laporan Keuangan',
                    'icon' => 'chart-bar',
                    'route' => 'laporan.billing',
                    'active' => 'laporan.billing',
                    'permission' => 'laporan.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Tiket',
            'icon' => 'ticket',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Daftar Tiket',
                    'icon' => 'ticket',
                    'route' => 'ticket.index',
                    'active' => ['ticket.index', 'ticket.show', 'ticket.create'],
                    'permission' => 'ticket.lihat',
                ],
                [
                    'title' => 'Riwayat Tiket',
                    'icon' => 'clock',
                    'route' => 'ticket.riwayat',
                    'active' => 'ticket.riwayat',
                    'permission' => 'ticket.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Jaringan',
            'icon' => 'server-stack',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Router',
                    'icon' => 'server',
                    'route' => 'router.index',
                    'active' => 'router.*',
                    'permission' => 'router.lihat',
                ],
                [
                    'title' => 'ODP',
                    'icon' => 'circle-stack',
                    'route' => 'odp.index',
                    'active' => 'odp.*',
                    'permission' => 'odp.lihat',
                ],
                [
                    'title' => 'IP Pool',
                    'icon' => 'circle-stack',
                    'route' => 'ip-pool.index',
                    'active' => 'ip-pool.*',
                    'permission' => 'ip_pool.lihat',
                ],
                [
                    'title' => 'IP Publik',
                    'icon' => 'globe-alt',
                    'route' => 'ip-publik.index',
                    'active' => 'ip-publik.*',
                    'permission' => 'ip_publik.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Inventaris',
            'icon' => 'archive-box',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Data Barang',
                    'icon' => 'archive-box',
                    'route' => 'barang.index',
                    'active' => 'barang.index',
                    'permission' => 'barang.lihat',
                ],
                [
                    'title' => 'Barang Masuk',
                    'icon' => 'arrow-down-on-square',
                    'route' => 'barang.masuk',
                    'active' => 'barang.masuk',
                    'permission' => 'barang.lihat',
                ],
                [
                    'title' => 'Barang Keluar',
                    'icon' => 'arrow-up-on-square',
                    'route' => 'barang.keluar',
                    'active' => 'barang.keluar',
                    'permission' => 'barang.lihat',
                ],
                [
                    'title' => 'Unit & Barcode',
                    'icon' => 'qr-code',
                    'route' => 'barang.unit',
                    'active' => 'barang.unit',
                    'permission' => 'barang.lihat',
                ],
            ],
        ],
        [
            'heading' => 'WhatsApp Blast',
            'icon' => 'chat-bubble-left-right',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Antrian Blast',
                    'icon' => 'queue-list',
                    'route' => 'sysblas.antrian.index',
                    'active' => 'sysblas.antrian.*',
                    'permission' => 'wa_gateway.lihat',
                ],
                [
                    'title' => 'Template Pesan',
                    'icon' => 'chat-bubble-bottom-center-text',
                    'route' => 'settings.whatsapp',
                    'active' => 'settings.whatsapp',
                    'permission' => 'wa_gateway.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Pengaturan Layanan & Tagihan',
            'icon' => 'adjustments-horizontal',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Paket Layanan',
                    'icon' => 'queue-list',
                    'route' => 'paket-layanan.index',
                    'active' => 'paket-layanan.*',
                    'permission' => 'paket_layanan.lihat',
                ],
                [
                    'title' => 'Profil Bandwidth',
                    'icon' => 'bolt',
                    'route' => 'profil-bandwidth.index',
                    'active' => 'profil-bandwidth.*',
                    'permission' => 'profil_bandwidth.lihat',
                ],
                [
                    'title' => 'Promo & Diskon',
                    'icon' => 'tag',
                    'route' => 'promo.index',
                    'active' => 'promo.*',
                    'permission' => 'promo.lihat',
                ],
                [
                    'title' => 'Siklus Tagihan',
                    'icon' => 'calendar-days',
                    'route' => 'billing.siklus-tagihan.index',
                    'active' => 'billing.siklus-tagihan.*',
                    'permission' => 'siklus_tagihan.ubah',
                ],
                [
                    'title' => 'Aturan Pengingat',
                    'icon' => 'bell-alert',
                    'route' => 'billing.aturan-pengingat.index',
                    'active' => 'billing.aturan-pengingat.*',
                    'permission' => 'invoice.lihat',
                ],
                [
                    'title' => 'Koneksi Gateway',
                    'icon' => 'cog',
                    'route' => 'settings.gateway',
                    'active' => 'settings.gateway',
                    'permission' => 'payment_gateway.lihat',
                ],
                [
                    'title' => 'Channel Pembayaran',
                    'icon' => 'credit-card',
                    'route' => 'settings.metode-pembayaran.index',
                    'active' => 'settings.metode-pembayaran.*',
                    'permission' => 'payment_gateway.lihat',
                ],
                [
                    'title' => 'Template Deskripsi Tagihan',
                    'icon' => 'document-text',
                    'route' => 'settings.template-deskripsi-tagihan',
                    'active' => 'settings.template-deskripsi-tagihan',
                    'permission' => 'payment_gateway.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Pengaturan Umum',
            'icon' => 'cog',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Profil Perusahaan',
                    'icon' => 'building-office',
                    'route' => 'settings.perusahaan',
                    'active' => 'settings.perusahaan',
                    'permission' => 'peran.lihat',
                ],
                [
                    'title' => 'Prefix Registrasi',
                    'icon' => 'tag',
                    'route' => 'settings.prefix-registrasi',
                    'active' => 'settings.prefix-registrasi',
                    'permission' => 'prefix_registrasi.lihat',
                ],
                [
                    'title' => 'Kota',
                    'icon' => 'building-office-2',
                    'route' => 'wilayah.kota.index',
                    'active' => 'wilayah.kota.*',
                    'permission' => 'wilayah.lihat',
                ],
                [
                    'title' => 'Kecamatan',
                    'icon' => 'map',
                    'route' => 'wilayah.kecamatan.index',
                    'active' => 'wilayah.kecamatan.*',
                    'permission' => 'wilayah.lihat',
                ],
                [
                    'title' => 'Kelurahan',
                    'icon' => 'map-pin',
                    'route' => 'wilayah.kelurahan.index',
                    'active' => 'wilayah.kelurahan.*',
                    'permission' => 'wilayah.lihat',
                ],
                [
                    'title' => 'Perumahan',
                    'icon' => 'home-modern',
                    'route' => 'wilayah.perumahan.index',
                    'active' => 'wilayah.perumahan.*',
                    'permission' => 'wilayah.lihat',
                ],
                [
                    'title' => 'Kategori & Kondisi',
                    'icon' => 'tag',
                    'route' => 'barang.pengaturan',
                    'active' => 'barang.pengaturan',
                    'permission' => 'barang.ubah',
                ],
                [
                    'title' => 'Koneksi WhatsApp',
                    'icon' => 'server-stack',
                    'route' => 'sysblas.koneksi.index',
                    'active' => 'sysblas.koneksi.*',
                    'permission' => 'wa_gateway.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Administrasi',
            'icon' => 'shield-check',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Pengguna',
                    'icon' => 'users',
                    'route' => 'users.index',
                    'active' => 'users.*',
                    'permission' => 'pengguna.lihat',
                ],
                [
                    'title' => 'Peran (Role)',
                    'icon' => 'shield-check',
                    'route' => 'roles.index',
                    'active' => 'roles.*',
                    'permission' => 'peran.lihat',
                ],
                [
                    'title' => 'Media Library',
                    'icon' => 'photo',
                    'route' => 'media-library.index',
                    'active' => 'media-library.*',
                    'permission' => 'media_library.lihat',
                ],
                [
                    'title' => 'Log Tugas Terjadwal',
                    'icon' => 'clock',
                    'route' => 'tugas-terjadwal.index',
                    'active' => 'tugas-terjadwal.*',
                    'permission' => 'tugas_terjadwal.lihat',
                ],
            ],
        ],
    ],
];
