<?php

return [
    'standalone' => [
        [
            'title' => 'Dashboard',
            'icon' => 'home',
            'route' => 'dashboard',
            'active' => 'dashboard',
            'permission' => null,
        ],
    ],
    'groups' => [
        [
            'heading' => 'Pelanggan & Layanan',
            'icon' => 'user-group',
            'expandable' => true,
            'expanded' => true,
            'items' => [
                [
                    'title' => 'List Kontak',
                    'icon' => 'user-group',
                    'route' => 'pelanggan.index',
                    'active' => 'pelanggan.*',
                    'permission' => 'pelanggan.lihat',
                ],
                [
                    'title' => 'Data Registrasi Billing',
                    'icon' => 'signal',
                    'route' => 'layanan-pelanggan.index',
                    'active' => 'layanan-pelanggan.*',
                    'permission' => 'layanan_pelanggan.lihat',
                ],
                [
                    'title' => 'Paket Layanan',
                    'icon' => 'queue-list',
                    'route' => 'paket-layanan.index',
                    'active' => 'paket-layanan.*',
                    'permission' => 'paket_layanan.lihat',
                ],
                [
                    'title' => 'Profil Bandwidth',
                    'icon' => 'bolt',
                    'route' => 'profil-bandwidth.index',
                    'active' => 'profil-bandwidth.*',
                    'permission' => 'profil_bandwidth.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Tiket & Operasional',
            'icon' => 'ticket',
            'expandable' => true,
            'expanded' => true,
            'items' => [
                [
                    'title' => 'Daftar Tiket',
                    'icon' => 'ticket',
                    'route' => 'ticket.index',
                    'active' => 'ticket.*',
                    'permission' => 'ticket.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Keuangan & Billing',
            'icon' => 'banknotes',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Tagihan (Invoice)',
                    'icon' => 'document-text',
                    'route' => 'invoice.index',
                    'active' => 'invoice.*',
                    'permission' => 'invoice.lihat',
                ],
                [
                    'title' => 'Riwayat Pembayaran',
                    'icon' => 'banknotes',
                    'route' => 'pembayaran.index',
                    'active' => 'pembayaran.index',
                    'permission' => 'pembayaran.lihat',
                ],
                [
                    'title' => 'Transaksi Gateway',
                    'icon' => 'credit-card',
                    'route' => 'pembayaran.transaksi-gateway.index',
                    'active' => 'pembayaran.transaksi-gateway.*',
                    'permission' => 'pembayaran.lihat',
                ],
                [
                    'title' => 'Promo & Diskon',
                    'icon' => 'tag',
                    'route' => 'promo.index',
                    'active' => 'promo.*',
                    'permission' => 'promo.lihat',
                ],
                [
                    'title' => 'Laporan Keuangan',
                    'icon' => 'chart-bar',
                    'route' => 'laporan.billing',
                    'active' => 'laporan.billing',
                    'permission' => 'laporan.lihat',
                ],
                [
                    'title' => 'Laporan Data Pelanggan',
                    'icon' => 'document-chart-bar',
                    'route' => 'laporan.data-pelanggan',
                    'active' => 'laporan.data-pelanggan',
                    'permission' => 'laporan.lihat',
                ],
                [
                    'title' => 'Aturan Pengingat',
                    'icon' => 'bell-alert',
                    'route' => 'billing.aturan-pengingat.index',
                    'active' => 'billing.aturan-pengingat.*',
                    'permission' => 'invoice.lihat',
                ],
                [
                    'title' => 'Siklus Tagihan',
                    'icon' => 'calendar-days',
                    'route' => 'billing.siklus-tagihan.index',
                    'active' => 'billing.siklus-tagihan.*',
                    'permission' => 'siklus_tagihan.ubah',
                ],
            ],
        ],
        [
            'heading' => 'Jaringan & Infrastruktur',
            'icon' => 'server-stack',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Router',
                    'icon' => 'server',
                    'route' => 'router.index',
                    'active' => 'router.*',
                    'permission' => 'router.lihat',
                ],
                [
                    'title' => 'IP Pool',
                    'icon' => 'circle-stack',
                    'route' => 'ip-pool.index',
                    'active' => 'ip-pool.*',
                    'permission' => 'ip_pool.lihat',
                ],
                [
                    'title' => 'IP Publik',
                    'icon' => 'globe-alt',
                    'route' => 'ip-publik.index',
                    'active' => 'ip-publik.*',
                    'permission' => 'ip_publik.lihat',
                ],
                [
                    'title' => 'ODP',
                    'icon' => 'circle-stack',
                    'route' => 'odp.index',
                    'active' => 'odp.*',
                    'permission' => 'odp.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Inventaris Barang',
            'icon' => 'cube',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Daftar Barang',
                    'icon' => 'cube',
                    'route' => 'barang.index',
                    'active' => 'barang.*',
                    'permission' => 'barang.lihat',
                ],
                [
                    'title' => 'Barang Masuk',
                    'icon' => 'arrow-down-tray',
                    'route' => 'barang-masuk.index',
                    'active' => 'barang-masuk.*',
                    'permission' => 'barang_masuk.lihat',
                ],
                [
                    'title' => 'Barang Keluar',
                    'icon' => 'arrow-up-tray',
                    'route' => 'barang-keluar.index',
                    'active' => 'barang-keluar.*',
                    'permission' => 'barang_keluar.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Maps & Estimasi Kabel',
            'icon' => 'map-pin',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Maps Lokasi',
                    'icon' => 'map',
                    'route' => 'maps.index',
                    'active' => 'maps.lokasi',
                    'permission' => 'pelanggan.lihat',
                ],
                [
                    'title' => 'Estimasi Kabel',
                    'icon' => 'calculator',
                    'route' => 'maps.estimasi-kabel',
                    'active' => 'maps.estimasi-kabel',
                    'permission' => 'pelanggan.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Area & Wilayah',
            'icon' => 'map',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Kota',
                    'icon' => 'building-office-2',
                    'route' => 'wilayah.kota.index',
                    'active' => 'wilayah.kota.*',
                    'permission' => 'wilayah.lihat',
                ],
                [
                    'title' => 'Kecamatan',
                    'icon' => 'map',
                    'route' => 'wilayah.kecamatan.index',
                    'active' => 'wilayah.kecamatan.*',
                    'permission' => 'wilayah.lihat',
                ],
                [
                    'title' => 'Kelurahan',
                    'icon' => 'map-pin',
                    'route' => 'wilayah.kelurahan.index',
                    'active' => 'wilayah.kelurahan.*',
                    'permission' => 'wilayah.lihat',
                ],
                [
                    'title' => 'Perumahan',
                    'icon' => 'home-modern',
                    'route' => 'wilayah.perumahan.index',
                    'active' => 'wilayah.perumahan.*',
                    'permission' => 'wilayah.lihat',
                ],
            ],
        ],
        [
            'heading' => 'SysBlast',
            'icon' => 'chat-bubble-left-right',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Koneksi API',
                    'icon' => 'server-stack',
                    'route' => 'sysblas.koneksi.index',
                    'active' => 'sysblas.koneksi.*',
                    'permission' => 'wa_gateway.lihat',
                ],
                [
                    'title' => 'Antrian Blast',
                    'icon' => 'queue-list',
                    'route' => 'sysblas.antrian.index',
                    'active' => 'sysblas.antrian.*',
                    'permission' => 'wa_gateway.lihat',
                ],
                [
                    'title' => 'Template Pesan',
                    'icon' => 'chat-bubble-bottom-center-text',
                    'route' => 'settings.whatsapp',
                    'active' => 'settings.whatsapp',
                    'permission' => 'wa_gateway.lihat',
                ],
            ],
        ],
        [
            'heading' => 'Administrasi',
            'icon' => 'shield-check',
            'expandable' => true,
            'expanded' => false,
            'items' => [
                [
                    'title' => 'Pengguna',
                    'icon' => 'users',
                    'route' => 'users.index',
                    'active' => 'users.*',
                    'permission' => 'pengguna.lihat',
                ],
                [
                    'title' => 'Peran (Role)',
                    'icon' => 'shield-check',
                    'route' => 'roles.index',
                    'active' => 'roles.*',
                    'permission' => 'peran.lihat',
                ],
                [
                    'title' => 'Profil Perusahaan',
                    'icon' => 'building-office',
                    'route' => 'settings.perusahaan',
                    'active' => 'settings.perusahaan',
                    'permission' => 'peran.lihat',
                ],
                [
                    'title' => 'Pengaturan Gateway',
                    'icon' => 'cog',
                    'route' => 'settings.gateway',
                    'active' => 'settings.gateway',
                    'permission' => 'payment_gateway.lihat',
                ],
                [
                    'title' => 'Prefix Registrasi',
                    'icon' => 'tag',
                    'route' => 'settings.prefix-registrasi',
                    'active' => 'settings.prefix-registrasi',
                    'permission' => 'prefix_registrasi.lihat',
                ],
                [
                    'title' => 'Media Library',
                    'icon' => 'photo',
                    'route' => 'media-library.index',
                    'active' => 'media-library.*',
                    'permission' => 'media_library.lihat',
                ],
                [
                    'title' => 'Jenis Barang',
                    'icon' => 'tag',
                    'route' => 'settings.jenis-barang',
                    'active' => 'settings.jenis-barang',
                    'permission' => 'pengaturan_barang.lihat',
                ],
                [
                    'title' => 'Kondisi Barang',
                    'icon' => 'tag',
                    'route' => 'settings.kondisi-barang',
                    'active' => 'settings.kondisi-barang',
                    'permission' => 'pengaturan_barang.lihat',
                ],
                [
                    'title' => 'Cabang Barang',
                    'icon' => 'tag',
                    'route' => 'settings.cabang-barang',
                    'active' => 'settings.cabang-barang',
                    'permission' => 'pengaturan_barang.lihat',
                ],
            ],
        ],
    ],
];
