[program:schedule]
process_name=%(program_name)s
command=/bin/bash -c "while [ true ]; do php /var/www/html/artisan schedule:run --verbose --no-interaction & sleep 60; wait; done"
directory=/var/www/html
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0